### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Resumen\n Estas funciones proporcionan información sobre el entorno en el que se produce el cálculo de Quantum."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Devuelve el número de qubits disponibles actualmente para tomar prestado.

    Esto incluye qubits sin usar; es decir, esto incluye el qubits devuelto `GetQubitsAvailableToUse`por.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Devuelve el número de qubits disponibles actualmente.
metadata:
  ms.openlocfilehash: bd6d442aabb179f4c5fea0a0f48efaa472ec00cf
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82673347"
