### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesingleconfigurationalstatesinglesiteoccupation
name: PrepareSingleConfigurationalStateSingleSiteOccupation
type: operation
namespace: microsoft.quantum.chemistry.jordanwigner
summary: Preparación de estado simple del estado de prueba mediante la que se ocupan las órbitas
syntax: 'operation PrepareSingleConfigurationalStateSingleSiteOccupation (qubitIndices : Int[], qubits : Qubit[]) : Unit'
input:
  content: '(qubitIndices : Int[], qubits : Qubit[])'
  types:
  - name: qubitIndices
    summary: Índices de qubits que van a ocupar los electrones.
    isArray: true
    isPrimitive: true
    uid: Int
  - name: qubits
    summary: Qubits de Hamiltonian.
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
functors:
- Adjoint
- Controlled
metadata:
  ms.openlocfilehash: 6ae72c826058288ba2318b0056cf017e571e216e
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89339395"
