### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: Devuelve el número de qubits disponibles actualmente.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      El número de qubits que se pueden asignar en una instrucción `using`.

      Si el equipo de destino que se usa no proporciona esta información, se devuelve `-1`.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
ms.openlocfilehash: 1cb1331aa26ec9755a9e379336f46387b61bb0ae
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/31/2019
ms.locfileid: "73230473"
