### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Resumen\n Estas funciones proporcionan información sobre el entorno en el que se produce el cálculo de Quantum."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Devuelve el número de qubits disponibles actualmente para tomar prestado.

    Esto incluye qubits sin usar; es decir, esto incluye el qubits devuelto por `GetQubitsAvailableToUse` .
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Devuelve el número de qubits disponibles actualmente.
metadata:
  ms.openlocfilehash: 7f597d8f429089b0ebf2c22cef1d1b98ea270402
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89341163"
