### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesingleconfigurationalstatesinglesiteoccupation
name: PrepareSingleConfigurationalStateSingleSiteOccupation
type: operation
namespace: Microsoft.Quantum.Chemistry.JordanWigner
summary: Preparación de estado simple del estado de prueba mediante la que se ocupan las órbitas
syntax: 'operation PrepareSingleConfigurationalStateSingleSiteOccupation (qubitIndices : Int[], qubits : Qubit[]) : Unit'
input:
  content: '(qubitIndices : Int[], qubits : Qubit[])'
  types:
  - name: qubitIndices
    summary: Índices de qubits que van a ocupar los electrones.
    isArray: true
    isPrimitive: true
    uid: Int
  - name: qubits
    summary: Qubits de Hamiltonian.
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
functors:
- Adjoint
- Controlled
metadata:
  ms.openlocfilehash: a7ed22f7f458a515cf1c19c54a841f8c16e317fe
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73231833"
