### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Devuelve el número de qubits disponibles actualmente para tomar prestado.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Devuelve el número de qubits disponibles actualmente.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Estas funciones proporcionan información sobre el entorno en el que se produce el cálculo de Quantum.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201451"
