### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesparsemulticonfigurationalstate
name: PrepareSparseMultiConfigurationalState
type: operation
namespace: microsoft.quantum.chemistry.jordanwigner
summary: La preparación del estado de prueba de la configuración de varias configuraciones múltiple, para lo que se agregan las excitaciones al estado de prueba inicial.
syntax: 'operation PrepareSparseMultiConfigurationalState (initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[]) : Unit'
input:
  content: '(initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[])'
  types:
  - name: initialStatePreparation
    summary: Unitario para preparar el estado de la prueba inicial.
    isOperation: true
    input:
      types:
      - isArray: true
        isPrimitive: true
        uid: Qubit
    output:
      types:
      - isPrimitive: true
        uid: Unit
  - name: excitations
    summary: Las exacciones del estado de prueba inicial representadas por la amplitud de los índices de excitation y qubit en los que actúa excitation.
    isArray: true
    uid: microsoft.quantum.chemistry.jordanwigner.jordanwignerinputstate
  - name: qubits
    summary: Qubits de Hamiltonian.
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
metadata:
  ms.openlocfilehash: cb4a90a4686c26139f956ae7438fd1da6b38897b
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89339310"
