### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Resumen\n Estas funciones proporcionan información sobre el entorno en el que se produce el cálculo de Quantum."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Devuelve el número de qubits disponibles actualmente para tomar prestado.

    Esto incluye qubits sin usar; es decir, esto incluye los qubits devueltos por `GetQubitsAvailableToUse`.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Devuelve el número de qubits disponibles actualmente.
metadata:
  ms.openlocfilehash: 50e5cfb7c1b9a4075c25b2705d00b435a09e159e
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73056824"
