### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Devuelve el número de qubits disponibles actualmente para tomar prestado.

  Esto incluye qubits sin usar; es decir, esto incluye los qubits devueltos por `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      El número de qubits que se pueden asignar en una instrucción `borrowing`.

      Si el equipo de destino que se usa no proporciona esta información, se devuelve `-1`.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
ms.openlocfilehash: c0caf866ad9a8773aa11ee7c6951ca3acc60cbaa
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/31/2019
ms.locfileid: "73230490"
