### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: Devuelve el número de qubits disponibles actualmente.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      El número de qubits que se pueden asignar en una `using` instrucción.

      Si el equipo de destino que se usa no proporciona esta información, `-1` se devuelve.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 82d8c27064cbb234b32707aa31fb0869f66ce23c
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682392"
